update CI/CD

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -20,27 +20,25 @@ deploy_to_vps:
     # Deploy to VPS
     - ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "echo 'SSH Connection Successful'"
     - ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
-    - cd ~/lms/lms-fe
-    # Backup thư mục build hiện tại
-    - echo "🔙 Creating backup of current build..."
-    - rm -rf .next_backup
-    - cp -r .next .next_backup || echo "⚠️ No previous build found, skipping backup."
-    # Pull code
-    - git pull origin develop
-    - cp .env.example .env
-    - npm install -f
-    # Build ứng dụng
-    - echo "🚧 Building the app..."
-    - if npm run build; then
-      - echo "✅ Build successful!"
-      - pm2 reload lms-web --update-env
-    - else
-      - echo "❌ Build failed! Rolling back to previous version..."
-      - rm -rf .next
-      - mv .next_backup .next || echo "⚠️ No backup found, rollback failed."
-      - pm2 reload lms-web --update-env
-      - exit 1
-    - fi
+      set -e
+      cd ~/lms/lms-fe
+      echo "🔙 Creating backup of current build..."
+      rm -rf .next_backup
+      cp -r .next .next_backup || echo "⚠️ No previous build found, skipping backup."
+      git pull origin develop
+      cp .env.example .env
+      npm install -f
+      echo "🚧 Building the app..."
+      if npm run build; then
+      echo "✅ Build successful!"
+      pm2 reload lms-web --update-env
+      else
+      echo "❌ Build failed! Rolling back to previous version..."
+      rm -rf .next
+      mv .next_backup .next || echo "⚠️ No backup found, rollback failed."
+      pm2 reload lms-web --update-env
+      exit 1
+      fi
     - EOF
 
   environment:
